#ifndef CB_INPUT_H
#define CB_INPUT_H

#include "../math/vec2.h"
#include "../types.h"

typedef enum {
  INPUT_KEY_UNKNOWN = -1,

  // Letters
  INPUT_KEY_A,
  INPUT_KEY_B,
  INPUT_KEY_C,
  INPUT_KEY_D,
  INPUT_KEY_E,
  INPUT_KEY_F,
  INPUT_KEY_G,
  INPUT_KEY_H,
  INPUT_KEY_I,
  INPUT_KEY_J,
  INPUT_KEY_K,
  INPUT_KEY_L,
  INPUT_KEY_M,
  INPUT_KEY_N,
  INPUT_KEY_O,
  INPUT_KEY_P,
  INPUT_KEY_Q,
  INPUT_KEY_R,
  INPUT_KEY_S,
  INPUT_KEY_T,
  INPUT_KEY_U,
  INPUT_KEY_V,
  INPUT_KEY_W,
  INPUT_KEY_X,
  INPUT_KEY_Y,
  INPUT_KEY_Z,

  // Numbers
  INPUT_KEY_0,
  INPUT_KEY_1,
  INPUT_KEY_2,
  INPUT_KEY_3,
  INPUT_KEY_4,
  INPUT_KEY_5,
  INPUT_KEY_6,
  INPUT_KEY_7,
  INPUT_KEY_8,
  INPUT_KEY_9,

  // Symbols
  INPUT_KEY_GRAVE,
  INPUT_KEY_MINUS,
  INPUT_KEY_EQUAL,
  INPUT_KEY_LEFT_BRACKET,
  INPUT_KEY_RIGHT_BRACKET,
  INPUT_KEY_BACKSLASH,
  INPUT_KEY_SEMICOLON,
  INPUT_KEY_APOSTROPHE,
  INPUT_KEY_COMMA,
  INPUT_KEY_PERIOD,
  INPUT_KEY_SLASH,

  // Control
  INPUT_KEY_ESCAPE,
  INPUT_KEY_ENTER,
  INPUT_KEY_TAB,
  INPUT_KEY_BACKSPACE,
  INPUT_KEY_INSERT,
  INPUT_KEY_DELETE,
  INPUT_KEY_HOME,
  INPUT_KEY_END,
  INPUT_KEY_PAGE_UP,
  INPUT_KEY_PAGE_DOWN,
  INPUT_KEY_SPACE,

  // Arrows
  INPUT_KEY_LEFT,
  INPUT_KEY_RIGHT,
  INPUT_KEY_UP,
  INPUT_KEY_DOWN,

  // Mods
  INPUT_KEY_LEFT_SHIFT,
  INPUT_KEY_RIGHT_SHIFT,
  INPUT_KEY_LEFT_CONTROL,
  INPUT_KEY_RIGHT_CONTROL,
  INPUT_KEY_LEFT_ALT,
  INPUT_KEY_RIGHT_ALT,
  INPUT_KEY_LEFT_SUPER,
  INPUT_KEY_RIGHT_SUPER,
  INPUT_KEY_MENU,

  // Locks
  INPUT_KEY_CAPS_LOCK,
  INPUT_KEY_NUM_LOCK,
  INPUT_KEY_SCROLL_LOCK,

  // Functions
  INPUT_KEY_F1,
  INPUT_KEY_F2,
  INPUT_KEY_F3,
  INPUT_KEY_F4,
  INPUT_KEY_F5,
  INPUT_KEY_F6,
  INPUT_KEY_F7,
  INPUT_KEY_F8,
  INPUT_KEY_F9,
  INPUT_KEY_F10,
  INPUT_KEY_F11,
  INPUT_KEY_F12,

  // Numeric Keyboard
  INPUT_KEY_KP_0,
  INPUT_KEY_KP_1,
  INPUT_KEY_KP_2,
  INPUT_KEY_KP_3,
  INPUT_KEY_KP_4,
  INPUT_KEY_KP_5,
  INPUT_KEY_KP_6,
  INPUT_KEY_KP_7,
  INPUT_KEY_KP_8,
  INPUT_KEY_KP_9,

  INPUT_KEY_KP_DECIMAL,
  INPUT_KEY_KP_DIVIDE,
  INPUT_KEY_KP_MULTIPLY,
  INPUT_KEY_KP_SUBTRACT,
  INPUT_KEY_KP_ADD,
  INPUT_KEY_KP_ENTER,
  INPUT_KEY_KP_EQUAL,

  INPUT_KEY_COUNT
} InputKey;

typedef enum {
  INPUT_MOUSE_BUTTON_LEFT,
  INPUT_MOUSE_BUTTON_RIGHT,
  INPUT_MOUSE_BUTTON_MIDDLE,

  INPUT_MOUSE_BUTTON_4,
  INPUT_MOUSE_BUTTON_5,
  INPUT_MOUSE_BUTTON_6,
  INPUT_MOUSE_BUTTON_7,
  INPUT_MOUSE_BUTTON_8,

  INPUT_MOUSE_BUTTON_COUNT
} InputMouseButton;

typedef struct {
  b8 current;
  b8 previous;
} InputState;

typedef struct {
  InputState keys[INPUT_KEY_COUNT];
  InputState mouse[INPUT_MOUSE_BUTTON_COUNT];
  Vec2 mouse_pos, mouse_delta;
  f32 mouse_wheel;
} Input;

void input_begin_frame(void);
Input *input_get_instance(void);

CB_API b8 input_key_pressed(InputKey key);
CB_API b8 input_key_down(InputKey key);
CB_API b8 input_key_released(InputKey key);

CB_API b8 input_mouse_btn_pressed(InputMouseButton btn);
CB_API b8 input_mouse_btn_down(InputMouseButton btn);
CB_API b8 input_mouse_btn_released(InputMouseButton btn);

CB_API Vec2 input_mouse_get_pos(void);
CB_API Vec2 input_mouse_get_delta(void);
CB_API f32 input_mouse_get_wheel(void);

#endif
